#ifndef JASONISNTHAPPY_H
#define JASONISNTHAPPY_H

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace jasonisnthappy {
#endif  // __cplusplus

/* Opaque pointer types */
typedef struct CDatabase CDatabase;
typedef struct CTransaction CTransaction;
typedef struct CCollection CCollection;
typedef struct CWatchHandle CWatchHandle;
typedef struct CWebServer CWebServer;

typedef struct CError {
  int32_t code;
  char *message;
} CError;

typedef struct {
  uintptr_t cache_size;
  uint64_t auto_checkpoint_threshold;
  uint32_t file_permissions;
  bool read_only;
} CDatabaseOptions;

typedef struct {
  uintptr_t max_retries;
  uint64_t retry_backoff_base_ms;
  uint64_t max_retry_backoff_ms;
} CTransactionConfig;

/**
 * C callback function type for run_transaction
 *
 * # Parameters
 * - tx: Transaction handle to use for operations
 * - user_data: User-provided context pointer
 *
 * # Returns
 * - 0 for success (commit), -1 for error (rollback)
 */
typedef int32_t (*transaction_callback_fn)(CTransaction *tx, void *user_data);

/**
 * C callback function type for watch events
 *
 * # Parameters
 * - collection: Name of the collection where the change occurred
 * - operation: "insert", "update", or "delete"
 * - doc_id: ID of the document
 * - doc_json: JSON representation of the document (NULL for delete operations)
 * - user_data: User-provided context pointer passed to watch_start
 */
typedef void (*watch_callback_fn)(const char *collection,
                                  const char *operation,
                                  const char *doc_id,
                                  const char *doc_json,
                                  void *user_data);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

CDatabase *jasonisnthappy_open(const char *path, CError *error_out);

CDatabase *jasonisnthappy_open_with_options(const char *path,
                                                  CDatabaseOptions options,
                                                  CError *error_out);

void jasonisnthappy_close(CDatabase *db);

int32_t jasonisnthappy_set_transaction_config(CDatabase *db,
                                              CTransactionConfig config,
                                              CError *error_out);

int32_t jasonisnthappy_get_transaction_config(CDatabase *db,
                                              CTransactionConfig *config_out,
                                              CError *error_out);

int32_t jasonisnthappy_set_auto_checkpoint_threshold(CDatabase *db,
                                                     uint64_t threshold,
                                                     CError *error_out);

CDatabaseOptions jasonisnthappy_default_database_options(void);

CTransactionConfig jasonisnthappy_default_transaction_config(void);

CTransaction *jasonisnthappy_begin_transaction(CDatabase *db, CError *error_out);

int32_t jasonisnthappy_commit(CTransaction *tx, CError *error_out);

void jasonisnthappy_rollback(CTransaction *tx);

/**
 * Run a transaction with automatic retries on conflict
 *
 * This is a convenience wrapper that handles begin/commit/rollback with automatic
 * retries according to the database's transaction config.
 *
 * # Parameters
 * - db: Database handle
 * - callback: Function called with the transaction - return 0 to commit, -1 to rollback
 * - user_data: Optional user context pointer passed to callback
 * - error_out: Output for error information
 *
 * # Returns
 * 0 on successful commit, -1 on error
 *
 * # Example
 * The callback should perform all operations and return 0 for success:
 * ```c
 * int32_t my_callback(CTransaction* tx, void* user_data) {
 *     // Do operations with tx
 *     return 0;  // success - will commit
 *     // return -1;  // error - will rollback
 * }
 * jasonisnthappy_run_transaction(db, my_callback, user_data, &error);
 * ```
 */
int32_t jasonisnthappy_run_transaction(CDatabase *db,
                                       transaction_callback_fn callback,
                                       void *user_data,
                                       CError *error_out);

/**
 * Check if a transaction is still active (not committed or rolled back)
 */
int32_t jasonisnthappy_transaction_is_active(CTransaction *tx, CError *error_out);

int32_t jasonisnthappy_insert(CTransaction *tx,
                              const char *collection_name,
                              const char *json,
                              char **id_out,
                              CError *error_out);

int32_t jasonisnthappy_find_by_id(CTransaction *tx,
                                  const char *collection_name,
                                  const char *id,
                                  char **json_out,
                                  CError *error_out);

int32_t jasonisnthappy_update_by_id(CTransaction *tx,
                                    const char *collection_name,
                                    const char *id,
                                    const char *json,
                                    CError *error_out);

int32_t jasonisnthappy_delete_by_id(CTransaction *tx,
                                    const char *collection_name,
                                    const char *id,
                                    CError *error_out);

int32_t jasonisnthappy_find_all(CTransaction *tx,
                                const char *collection_name,
                                char **json_out,
                                CError *error_out);

void jasonisnthappy_free_string(char *s);

void jasonisnthappy_free_error(CError error);

int32_t jasonisnthappy_count(CTransaction *tx,
                             const char *collection_name,
                             uint64_t *count_out,
                             CError *error_out);

int32_t jasonisnthappy_create_collection(CTransaction *tx,
                                         const char *collection_name,
                                         CError *error_out);

int32_t jasonisnthappy_drop_collection(CTransaction *tx,
                                       const char *collection_name,
                                       CError *error_out);

int32_t jasonisnthappy_rename_collection(CTransaction *tx,
                                         const char *old_name,
                                         const char *new_name,
                                         CError *error_out);

int32_t jasonisnthappy_list_collections(CDatabase *db,
                                        char **json_out,
                                        CError *error_out);

/**
 * List all indexes for a collection
 *
 * Returns JSON array of index objects with: name, fields (array), unique (bool), btree_root
 */
int32_t jasonisnthappy_list_indexes(CDatabase *db,
                                    const char *collection_name,
                                    char **json_out,
                                    CError *error_out);

int32_t jasonisnthappy_create_index(CDatabase *db,
                                    const char *collection_name,
                                    const char *index_name,
                                    const char *field,
                                    bool unique,
                                    CError *error_out);

int32_t jasonisnthappy_create_compound_index(CDatabase *db,
                                             const char *collection_name,
                                             const char *index_name,
                                             const char *const *fields,
                                             uintptr_t num_fields,
                                             bool unique,
                                             CError *error_out);

int32_t jasonisnthappy_create_text_index(CDatabase *db,
                                         const char *collection_name,
                                         const char *index_name,
                                         const char *const *fields,
                                         uintptr_t num_fields,
                                         CError *error_out);

int32_t jasonisnthappy_drop_index(CDatabase *db,
                                  const char *collection_name,
                                  const char *index_name,
                                  CError *error_out);

int32_t jasonisnthappy_collection_stats(CDatabase *db,
                                        const char *collection_name,
                                        char **json_out,
                                        CError *error_out);

int32_t jasonisnthappy_database_info(CDatabase *db, char **json_out, CError *error_out);

int32_t jasonisnthappy_get_path(CDatabase *db, char **path_out, CError *error_out);

int32_t jasonisnthappy_is_read_only(CDatabase *db, CError *error_out);

uintptr_t jasonisnthappy_max_bulk_operations(CDatabase *db, CError *error_out);

uintptr_t jasonisnthappy_max_document_size(CDatabase *db, CError *error_out);

uintptr_t jasonisnthappy_max_request_body_size(CDatabase *db, CError *error_out);

int32_t jasonisnthappy_set_schema(CDatabase *db,
                                  const char *collection_name,
                                  const char *schema_json,
                                  CError *error_out);

int32_t jasonisnthappy_get_schema(CDatabase *db,
                                  const char *collection_name,
                                  char **schema_json_out,
                                  CError *error_out);

int32_t jasonisnthappy_remove_schema(CDatabase *db,
                                     const char *collection_name,
                                     CError *error_out);

CCollection *jasonisnthappy_get_collection(CDatabase *db,
                                                 const char *collection_name,
                                                 CError *error_out);

void jasonisnthappy_collection_free(CCollection *coll);

int32_t jasonisnthappy_collection_upsert_by_id(CCollection *coll,
                                               const char *id,
                                               const char *json,
                                               int32_t *result_out,
                                               char **id_out,
                                               CError *error_out);

int32_t jasonisnthappy_collection_upsert(CCollection *coll,
                                         const char *query,
                                         const char *json,
                                         int32_t *result_out,
                                         char **id_out,
                                         CError *error_out);

int32_t jasonisnthappy_collection_find(CCollection *coll,
                                       const char *query,
                                       char **json_out,
                                       CError *error_out);

int32_t jasonisnthappy_collection_find_one(CCollection *coll,
                                           const char *query,
                                           char **json_out,
                                           CError *error_out);

int32_t jasonisnthappy_collection_update(CCollection *coll,
                                         const char *query,
                                         const char *updates_json,
                                         uintptr_t *count_out,
                                         CError *error_out);

int32_t jasonisnthappy_collection_update_one(CCollection *coll,
                                             const char *query,
                                             const char *updates_json,
                                             bool *updated_out,
                                             CError *error_out);

int32_t jasonisnthappy_collection_delete(CCollection *coll,
                                         const char *query,
                                         uintptr_t *count_out,
                                         CError *error_out);

int32_t jasonisnthappy_collection_delete_one(CCollection *coll,
                                             const char *query,
                                             bool *deleted_out,
                                             CError *error_out);

int32_t jasonisnthappy_collection_insert_many(CCollection *coll,
                                              const char *docs_json,
                                              char **ids_json_out,
                                              CError *error_out);

int32_t jasonisnthappy_collection_distinct(CCollection *coll,
                                           const char *field,
                                           char **json_out,
                                           CError *error_out);

int32_t jasonisnthappy_collection_count_distinct(CCollection *coll,
                                                 const char *field,
                                                 uintptr_t *count_out,
                                                 CError *error_out);

int32_t jasonisnthappy_collection_search(CCollection *coll,
                                         const char *query,
                                         char **json_out,
                                         CError *error_out);

int32_t jasonisnthappy_collection_insert(CCollection *coll,
                                         const char *json,
                                         char **id_out,
                                         CError *error_out);

int32_t jasonisnthappy_collection_find_by_id(CCollection *coll,
                                             const char *id,
                                             char **json_out,
                                             CError *error_out);

int32_t jasonisnthappy_collection_update_by_id(CCollection *coll,
                                               const char *id,
                                               const char *updates_json,
                                               CError *error_out);

int32_t jasonisnthappy_collection_delete_by_id(CCollection *coll,
                                               const char *id,
                                               CError *error_out);

int32_t jasonisnthappy_collection_find_all(CCollection *coll,
                                           char **json_out,
                                           CError *error_out);

int32_t jasonisnthappy_collection_count(CCollection *coll,
                                        uintptr_t *count_out,
                                        CError *error_out);

int32_t jasonisnthappy_collection_name(CCollection *coll,
                                       char **name_out,
                                       CError *error_out);

int32_t jasonisnthappy_collection_count_with_query(CCollection *coll,
                                                   const char *query,
                                                   uintptr_t *count_out,
                                                   CError *error_out);

int32_t jasonisnthappy_collection_insert_typed(CCollection *coll,
                                               const char *json,
                                               char **id_out,
                                               CError *error_out);

int32_t jasonisnthappy_collection_insert_many_typed(CCollection *coll,
                                                    const char *docs_json,
                                                    char **ids_json_out,
                                                    CError *error_out);

int32_t jasonisnthappy_collection_find_by_id_typed(CCollection *coll,
                                                   const char *id,
                                                   char **json_out,
                                                   CError *error_out);

int32_t jasonisnthappy_collection_find_all_typed(CCollection *coll,
                                                 char **json_out,
                                                 CError *error_out);

int32_t jasonisnthappy_collection_find_typed(CCollection *coll,
                                             const char *query,
                                             char **json_out,
                                             CError *error_out);

int32_t jasonisnthappy_collection_find_one_typed(CCollection *coll,
                                                 const char *query,
                                                 char **json_out,
                                                 CError *error_out);

int32_t jasonisnthappy_collection_update_by_id_typed(CCollection *coll,
                                                     const char *id,
                                                     const char *updates_json,
                                                     CError *error_out);

int32_t jasonisnthappy_collection_update_typed(CCollection *coll,
                                               const char *query,
                                               const char *updates_json,
                                               uintptr_t *count_out,
                                               CError *error_out);

int32_t jasonisnthappy_collection_update_one_typed(CCollection *coll,
                                                   const char *query,
                                                   const char *updates_json,
                                                   bool *updated_out,
                                                   CError *error_out);

int32_t jasonisnthappy_collection_upsert_by_id_typed(CCollection *coll,
                                                     const char *id,
                                                     const char *json,
                                                     int32_t *result_out,
                                                     char **id_out,
                                                     CError *error_out);

int32_t jasonisnthappy_collection_upsert_typed(CCollection *coll,
                                               const char *query,
                                               const char *json,
                                               int32_t *result_out,
                                               char **id_out,
                                               CError *error_out);

/**
 * Query with all options in a single call (simplified query builder for FFI)
 *
 * # Parameters
 * - filter: Optional query filter string (NULL = no filter)
 * - sort_field: Optional field to sort by (NULL = no sort)
 * - sort_ascending: true for ascending, false for descending
 * - limit: Max results (0 = no limit)
 * - skip: Skip N results (0 = no skip)
 * - project_json: Optional JSON array of fields to include (NULL = all fields)
 * - exclude_json: Optional JSON array of fields to exclude (NULL = none)
 *
 * Note: Cannot specify both project_json and exclude_json
 */
int32_t jasonisnthappy_collection_query_with_options(CCollection *coll,
                                                     const char *filter,
                                                     const char *sort_field,
                                                     bool sort_ascending,
                                                     uintptr_t limit,
                                                     uintptr_t skip,
                                                     const char *project_json,
                                                     const char *exclude_json,
                                                     char **json_out,
                                                     CError *error_out);

/**
 * Query and count results (no fetch)
 */
int32_t jasonisnthappy_collection_query_count(CCollection *coll,
                                              const char *filter,
                                              uintptr_t skip,
                                              uintptr_t limit,
                                              uintptr_t *count_out,
                                              CError *error_out);

/**
 * Query and return first result
 */
int32_t jasonisnthappy_collection_query_first(CCollection *coll,
                                              const char *filter,
                                              const char *sort_field,
                                              bool sort_ascending,
                                              char **json_out,
                                              CError *error_out);

/**
 * Execute bulk write operations in a single transaction
 *
 * # Parameters
 * - operations_json: JSON array of operations, each with:
 *   - "op": "insert" | "update_one" | "update_many" | "delete_one" | "delete_many"
 *   - "doc": document (for insert)
 *   - "query": query string (for update/delete)
 *   - "updates": updates object (for update)
 * - ordered: if true, stop on first error; if false, continue on errors
 * - result_json_out: BulkWriteResult as JSON (inserted_count, updated_count, deleted_count, errors)
 *
 * # Example operations_json:
 * ```json
 * [
 *   {"op": "insert", "doc": {"name": "Alice", "age": 30}},
 *   {"op": "update_one", "query": "name is 'Bob'", "updates": {"age": 31}},
 *   {"op": "delete_many", "query": "age < 18"}
 * ]
 * ```
 */
int32_t jasonisnthappy_collection_bulk_write(CCollection *coll,
                                             const char *operations_json,
                                             bool ordered,
                                             char **result_json_out,
                                             CError *error_out);

/**
 * Execute an aggregation pipeline
 *
 * # Parameters
 * - pipeline_json: JSON array of pipeline stages, each with:
 *   - "match": query string (filter stage)
 *   - "group_by": {field: "...", accumulators: [{type: "count|sum|avg|min|max", output_field: "...", field: "..."}]}
 *   - "sort": {field: "...", ascending: true|false}
 *   - "limit": number
 *   - "skip": number
 *   - "project": ["field1", "field2", ...]
 *   - "exclude": ["field1", "field2", ...]
 *
 * # Example pipeline_json:
 * ```json
 * [
 *   {"match": "status is 'active'"},
 *   {"group_by": {"field": "city", "accumulators": [
 *     {"type": "count", "output_field": "total"},
 *     {"type": "sum", "field": "amount", "output_field": "total_amount"}
 *   ]}},
 *   {"sort": {"field": "total", "ascending": false}},
 *   {"limit": 10}
 * ]
 * ```
 */
int32_t jasonisnthappy_collection_aggregate(CCollection *coll,
                                            const char *pipeline_json,
                                            char **result_json_out,
                                            CError *error_out);

/**
 * Start watching a collection for changes
 *
 * Creates a background thread that monitors changes to the collection and calls
 * the provided callback function for each change event.
 *
 * # Parameters
 * - coll: Collection to watch
 * - filter: Optional query filter (NULL = watch all changes)
 * - callback: Function to call for each change event
 * - user_data: Optional user context pointer passed to callback
 * - handle_out: Output pointer for the watch handle (use to stop watching)
 *
 * # Returns
 * 0 on success, -1 on error
 *
 * # Safety
 * The callback will be called from a background thread. Ensure thread safety.
 * Call jasonisnthappy_watch_stop() to stop watching and clean up the thread.
 */
int32_t jasonisnthappy_collection_watch_start(CCollection *coll,
                                              const char *filter,
                                              watch_callback_fn callback,
                                              void *user_data,
                                              CWatchHandle **handle_out,
                                              CError *error_out);

/**
 * Stop watching and clean up resources
 *
 * Signals the background thread to stop and waits for it to finish.
 * After calling this, the handle pointer is no longer valid.
 *
 * # Parameters
 * - handle: Watch handle returned by jasonisnthappy_collection_watch_start
 *
 * # Safety
 * The handle must have been created by jasonisnthappy_collection_watch_start.
 * Do not use the handle after calling this function.
 */
void jasonisnthappy_watch_stop(CWatchHandle *handle);

int32_t jasonisnthappy_checkpoint(CDatabase *db, CError *error_out);

int32_t jasonisnthappy_backup(CDatabase *db,
                              const char *backup_path,
                              CError *error_out);

int32_t jasonisnthappy_verify_backup(CDatabase *db,
                                     const char *backup_path,
                                     char **json_out,
                                     CError *error_out);

int32_t jasonisnthappy_garbage_collect(CDatabase *db,
                                       char **json_out,
                                       CError *error_out);

int32_t jasonisnthappy_metrics(CDatabase *db, char **json_out, CError *error_out);

int32_t jasonisnthappy_frame_count(CDatabase *db,
                                   uint64_t *count_out,
                                   CError *error_out);

struct CWebServer *jasonisnthappy_start_web_server(CDatabase *db,
                                                   const char *addr,
                                                   CError *error_out);

void jasonisnthappy_stop_web_server(struct CWebServer *server);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace jasonisnthappy
#endif  // __cplusplus

#endif  /* JASONISNTHAPPY_H */
